services:
  manticore:
    image: manticoresearch/manticore:latest
    container_name: manticore
    ports:
      - "${MANTICORE_PORT}:9306"
    volumes:
      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
      - ./manticore/idx:/var/lib/manticore
      - ./datasets:/datasets
    env_file:
      - .env